version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: calbearadmin # Replace with your desired username
      POSTGRES_PASSWORD: calebear123 # Replace with your desired password
      POSTGRES_DB: calebear # Replace with your desired database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 